version = 0.1

[default.deploy.parameters]
stack_name = "aws-serverless-app"
resolve_s3 = true
s3_prefix = "aws-serverless-app"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
